package com.shortener.link.infrastructure.persistence.dynamo.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.shortener.link.domain.value_objects.Guid;
import com.shortener.link.domain.value_objects.Url;

import java.util.Date;

@DynamoDBTable(tableName = "links")
public class LinkEntity {
    @DynamoDBHashKey
    @DynamoDBTypeConverted(converter = GuidConverter.class)
    public Guid id;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = UrlConverter.class)
    public Url originalUrl;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "short-url-hash-index")
    public String shortHash;

    @DynamoDBAttribute
    public Integer duration;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public Date createdAt;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    public Date updatedAt;

    public LinkEntity(Guid id, Url originalUrl, String shortHash, Integer duration, Date createdDate) {
        this.id = id;
        this.originalUrl = originalUrl;
        this.shortHash = shortHash;
        this.duration = duration;
        this.createdAt = createdDate;
    }
}

class UrlConverter implements DynamoDBTypeConverter<Url, String> {
    public Url convert(String value) {
        return new Url(value);
    }

    public String unconvert(Url url) {
        return url.toString();
    }
}

class GuidConverter implements DynamoDBTypeConverter<Guid, String> {
    public Guid convert(String value) {
        return Guid.fromString(value);
    }

    public String unconvert(Guid guid) {
        return guid.toString();
    }
}